# Generated by Django 5.0.6 on 2024-07-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_rename_name_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_image',
            field=models.ImageField(upload_to='products_images'),
        ),
    ]
