# Generated by Django 5.0.6 on 2024-07-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_products_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=40)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SizeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=40)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='color_variants',
            field=models.ManyToManyField(blank=True, to='ecommerce.colorvariant'),
        ),
        migrations.AddField(
            model_name='products',
            name='size_variants',
            field=models.ManyToManyField(blank=True, to='ecommerce.sizevariant'),
        ),
    ]
