# Generated by Django 5.0.6 on 2024-07-20 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_building_account_country_account_house_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='building',
        ),
        migrations.RemoveField(
            model_name='account',
            name='country',
        ),
        migrations.RemoveField(
            model_name='account',
            name='house',
        ),
        migrations.RemoveField(
            model_name='account',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='account',
            name='state',
        ),
        migrations.RemoveField(
            model_name='account',
            name='street',
        ),
        migrations.RemoveField(
            model_name='account',
            name='zip',
        ),
    ]
